### ISSUE TITLE
PyCapsule_New called with null pointer

### ISSUE THREAD

**Issue by johndoe31415** [DinoTools/sslscan#15]
Working with GIT 1328b490 (1.10.0) compiled against OpenSSL 1.0.1e 11 Feb 2013 with Python3.2m on Debian Wheezy x86_64 I get the following error when scanning:

<pre>
  $ sslscan google.de
  Loaded 'test' successfully
  Loaded 'legacy_xml' successfully
  Loaded 'report' successfully
  Loaded 'legacy' successfully
                   _
           ___ ___| |___  ___ __ _ _ __
          / __/ __| / __|/ __/ _` | '_ \
          \__ \__ \ \__ \ (_| (_| | | | |
          |___/___/_|___/\___\__,_|_| |_|

        sslscan version 1.10.0 
        OpenSSL 1.0.1e 11 Feb 2013

  Testing SSL server google.de on port 443

  Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/sslscan/__init__.py", line 83, in run
    handlers = [tmp()]
  File "/usr/local/lib/python3.2/dist-packages/sslscan/handler/output/legacy.py", line 11, in __init__
    Output.__init__(self)
  File "/usr/local/lib/python3.2/dist-packages/sslscan/handler/__init__.py", line 9, in __init__
    self.config = OutputConfig(g_config)
  File "/usr/local/lib/python3.2/dist-packages/sslscan/__init__.py", line 410, in __init__
    for name in names:
  ValueError: PyCapsule_New called with null pointer
</pre>

The error occurs every time regardless of the server I'm trying to use. Any ideas?

**Comment by johndoe31415** [comment]
Just bisected the bug:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
282d488bafb9a02ccae2673a78d2f2b06954b9a5
205f7ad604ec307fe80b292956e6e20860be13f3
We cannot bisect more!

**Comment by johndoe31415** [comment]
No feedback, closing this.
